TRAIN_DATA_PATH = "./data/adult.csv"
TEST_DATA_PATH = "./data/test.csv"
BASIC_MODEL_PATH = "./models/logistic.joblib"
DECISION_TREE_MODEL_PATH = "./models/decision.joblib"
KNN_MODEL_PATH = "./models/knn.joblib"